---
title: "Linear Models"
author: "Yue Liu"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document

---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Import the data 

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group
  ) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighbourhood, room_type)
```

## Fit a model

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) +
  geom_point()
```

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

Lets's look at the results...

```{r,include = FALSE}
summary(fit)

summary(fit)$coef

coef(fit)

fitted.values(fit)

residuals(fit)
```

Let's look at the results better...

```{r}
broom::glance(fit)

broom::tidy(fit) %>% 
# for a 1 unit increase in stars -> expect the price increase 32 dollars, keeping the borough fixed 
# reference group - Bronx
# Brooklyn 40.5 dollars more expensive than Bronx
  select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "borough","Borough: " )
  ) %>% 
  knitr::kable(digits = 3)
```

## Be in control of factors 

factors are in alphabetic order -> change the reference group... 

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    borough = fct_infreq(borough), # in order of frequency of borough
    room_type = fct_infreq(borough)
  )
```

look at the plot again 

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) +
  geom_point()
```

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)

broom::tidy(fit)
```

## Diagnostics 

```{r}
# residuals(fit)
nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = borough, y = resid)) +
  geom_violin() +
  ylim(-500, 1500)

nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = stars, y = resid)) + 
  geom_point()+
  facet_wrap(. ~ borough)
```

## Hypothesis test

This does t-test by default 

```{r}
fit %>% 
  broom::tidy()
```

What about significance of `borough`

```{r}
fit_null = lm(price ~ stars, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough, data = nyc_airbnb)

anova(fit_null, fit_alt) %>% 
  broom::tidy()
```

## Nest data, fit models 

```{r}
fit = lm(price ~ stars * borough + room_type * borough, data = nyc_airbnb)

broom::tidy(fit)
```

more exploratory but more easier to understand 

```{r}
nest_lm_res =
  nyc_airbnb %>% 
  nest(data = -borough) %>% 
  mutate(
    models = map(data, ~lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)) %>% 
  select(-data, -models) %>% 
  unnest(results)

nest_lm_res %>% 
  select(borough, term, estimate) %>% 
  mutate(term = fct_inorder(term)) %>% 
  pivot_wider(
    names_from = term, values_from = estimate) %>% 
  knitr::kable(digits = 3)
```

```{r}
nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  nest(data = -neighbourhood) %>% 
  mutate(
    models = map(.x = data, ~lm(price ~ stars + room_type, data =.x)),
    results = map(models, broom::tidy)
  ) %>% 
  select(-data, -models) %>% 
  unnest(results) %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighbourhood, y = estimate)) + 
  geom_point() + 
  facet_wrap(. ~ term) + 
  theme(axis.text.x = element_text(angle = 70, vjust = 0.5, hjust=1))

```

